### ISSUE TITLE
New notification draining battery significantly

### ISSUE THREAD

**Issue by abrahimladha** [matrix-org/matrix-android-sdk#27]
The new update has this unremovable notification as compared to other messaging apps. My stats say it drains on average 16% of my battery in a day running in the background, as compared to previously 3%. 
![tmp_29740-screenshot_20151130-2047401116979452](https://cloud.githubusercontent.com/assets/6496702/11490154/f8b13666-97a3-11e5-82c7-88fa4550e342.png)

**Comment by Kegsay** [comment]
This is because it has an open TCP connection (hence the persistent notification) which isn't great for your battery. You should enable GCM notifications on the Settings page so you can receive push notifications instead. This is much better for battery life.

If you cannot enable GCM notifications, please submit a bug report from inside the app, thanks!
