### ISSUE TITLE
[Question] Are SonarQube fixes welcome?

### ISSUE THREAD

**Issue by dvmarcilio** [matrix-org/matrix-android-sdk#466]
Hi,

I'm found the project on SonarCloud, and I'm willing to contribute with fixes for some kind of issues. Is that something of interest for the project? If so, should I just submit pull requests? (I'm aware of the necessity of signing off commits and also providing a changelog entry).

Thanks!

**Comment by bmarty** [comment]
Hi, sorry for the late answer.
The core team is now working on RiotX (https://github.com/vector-im/riotX-android).
SonarCloud issue fixes (by PRs) will be more appreciated for RiotX :)
RiotX sonarcloud project: https://sonarcloud.io/dashboard?id=vector.android.riotx
Please note that I will trigger an analysis because the last one is from April
Thanks
Benoît
